spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #是否与法务发现组件进行结合,通过serviceId转发到具体的服务实例,默认为false
          lower-case-service-id: true #当注册中心为eureka时,设置为true表示开启用小写的serviceId进行基于服务路由的转发

server:
  port: 8070

logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
