spring:
  application:
    name: product-service
server:
  port: 7070

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
